# Site setings
name: "Benoît Patra's blog"
title: "Benoît Patra's blog"
tagline: "Discussions on software engineering"
description: 'Discussions on software engineering and machine learning'

url: https://www.benoitpatra.com # required by seo-tag plugins and others
baseurl: 
exclude:
  - jekyll-ignore

# Add your GA Tracking Id
ga_analytics: UA-71053026-1

disqus: benoitpatra

# used by both template and Jekyll SEO TAG pluging
logo: '/assets/images/logo.png'

# jekyll-seo-tag
author:
  name: Benoit Patra
  twitter: benoitpatra
  image: 'authorimage2.jpg'
  # theme
  greetings: "Hi, I am Benoît Patra, welcome to my personal blog."


#Social for Jekyll SEO
social:
  name: Benoît Patra
  links:
    - https://twitter.com/benoitpatra
    - https://www.linkedin.com/in/benoit-patra
    - https://github.com/bpatra

# used by both theme and SEO-tag
twitter:
  username: benoitpatra # used by theme
  card: summary_large_image

# Social links for template
github: 'bpatra'
linkedin: 'benoit-patra'
feed: 'feed.xml'

jekyll-archives:
  enabled:
    - month
    - categories
    - tags
  layouts: archive
  permalinks:
    month: '/:year/:month/'
    category: '/category/:name/'
    tags: '/tag/:tag/'

# Navigation
navigation:
  - text: Home
    url: /
  - text: Archives
    url: /archives/
  - text: About
    url: /about/
  - text: Academic (past)
    url: /academic/

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:year/:month/:day/:title/

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
