# Site setings
name: "Benoît Patra's blog"
description: 'Discussions on software engineering and machine learning'
meta_description: 'Software engineering, machine learning, datascience, CTO'
logo:
# Author image is used in site sidebar and greetings in the home page hero text
author:
  image: 'authorimage.jpg'
  greetings: "Hi, I am Benoît Patra, welcome to my personal blog."

baseurl: 
production_url: https://www.benoitpatra.com/
exclude:
  - jekyll-ignore

# Add your GA Tracking Id
ga_analytics: UA-71053026-1

disqus: benoitpatra

# Social links
twitter: 'benoitpatra'
github: 'bpatra'
linkedin: 'benoit-patra'
feed: 'feed.xml'

jekyll-archives:
  enabled:
    - month
    - categories
    - tags
  layouts: archive
  permalinks:
    month: '/:year/:month/'
    category: '/category/:name/'
    tags: '/tag/:tag/'

# Navigation
navigation:
  - text: Home
    url: /
  - text: Archives
    url: /archives
  - text: About
    url: /about

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:year/:month/:day/:title/

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
